
SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
from [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA]) 
from [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [TABELA DE CLIENTES]
SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT CONCAT
	(
		'O CLIENTE ', UPPER(TC.NOME), ' FATUROU R$ ', 
		CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(INF.[QUANTIDADE] * INF.[PREÇO]))),
		' NO ANO DE ', CONVERT(VARCHAR, YEAR(NF.[DATA])) 
	) AS SENTENCA
FROM [NOTAS FISCAIS] NF
	INNER JOIN [TABELA DE CLIENTES] TC
		ON NF.[CPF] = TC.[CPF]
	INNER JOIN [ITENS NOTAS FISCAIS] INF
		ON NF.[NUMERO] = INF.[NUMERO]
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY TC.[NOME], YEAR(NF.[DATA])