
SELECT CEILING(12.333223)

SELECT FLOOR(12.333223)

SELECT RAND()

SELECT ROUND(12.33323323, 2)

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),1) FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT YEAR(NF.[DATA]) AS ANO, FLOOR(SUM(NF.[IMPOSTO] * (INF.[QUANTIDADE] * INF.[PREÇO]))) AS LUCRO
FROM [NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY YEAR(NF.[DATA])