

SELECT * FROM [TABELA DE PRODUTOS] TP

SELECT * FROM [NOTAS FISCAIS] NF

SELECT * FROM [ITENS NOTAS FISCAIS] INF

SELECT TP.SABOR, NF.DATA, (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO

SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR(NF.DATA)

SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA)

SELECT YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)

SELECT AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO
, CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + ' %' 
AS PERCENTUAL FROM
(SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA)) AUX1
INNER JOIN (SELECT YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC
















-- RELATORIO DE FATURAMENTO TOTAL NO ANO DE 2016 POR SABOR
-- E A PORCENTAGEM REFERENTE AO LUCRO TOTAL DA EMPRESA

SELECT * FROM [TABELA DE PRODUTOS]
SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [ITENS NOTAS FISCAIS]

-- SELECIONANDO OS CAMPOS NECESSÁRIOS DE CADA TABELA
SELECT TP.[SABOR] FROM [TABELA DE PRODUTOS] TP
SELECT NF.[DATA] FROM [NOTAS FISCAIS] NF
SELECT (INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS] INF

-- FAZENDO O JOIN DAS TRES TABELAS
SELECT TP.[SABOR], NF.[DATA], (INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF
	INNER JOIN [TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF
		ON INF.[NUMERO] = NF.[NUMERO]


--FILTRANDO PELO ANO DESEJADO E AGRUPANDO POR SABOR
SELECT TP.[SABOR], YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF
	INNER JOIN [TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF
		ON INF.[NUMERO] = NF.[NUMERO]
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY TP.[SABOR], YEAR(NF.[DATA])

-- ACHANDO O VALOR TOTAL DE FATURAMENTO
-- A QUERY ANTERIOR, SEM A DIVISÃO DE SABORES, ME DÁ ESSE FATURAMENTO

SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF
	INNER JOIN [TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] NF
		ON INF.[NUMERO] = NF.[NUMERO]
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY YEAR(NF.[DATA])


-- UNINDO AS DUAS QUERYS UTILIZANDO O ANO COMO FATOR COMUM
-- ISSO TRARÁ UMA REPETIÇÃO DO VALOR TOTAL PARA CADA LINHA PREPARANDO A QUERY PARA O CALCULO FINAL

SELECT AUX1.[SABOR], AUX1.[ANO], AUX1.[FATURAMENTO], AUX2.[TOTAL]
FROM
	(SELECT TP.[SABOR], YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
	FROM [ITENS NOTAS FISCAIS] INF
		INNER JOIN [TABELA DE PRODUTOS] TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
		INNER JOIN [NOTAS FISCAIS] NF
			ON INF.[NUMERO] = NF.[NUMERO]
	WHERE YEAR(NF.[DATA]) = 2016
	GROUP BY TP.[SABOR], YEAR(NF.[DATA])) AUX1 -- QUERY AUXILIAR 1
	INNER JOIN
		(SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS TOTAL
		FROM [ITENS NOTAS FISCAIS] INF
			INNER JOIN [TABELA DE PRODUTOS] TP
				ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
			INNER JOIN [NOTAS FISCAIS] NF
				ON INF.[NUMERO] = NF.[NUMERO]
		WHERE YEAR(NF.[DATA]) = 2016
		GROUP BY YEAR(NF.[DATA])) AUX2 -- QUERY AUXILIAR 2
	ON AUX1.[ANO] = AUX2.[ANO]

-- FAZENDO O CALCULO FINAL DO PERCENTUAL DE PARTICIPAÇÃO DE CADA SABOR

SELECT 
	AUX1.[SABOR], 
	AUX1.[ANO], 
	CONVERT(DECIMAL(15,2), AUX1.[FATURAMENTO]) AS FATURAMENTO, 
	CONCAT
		(
			CONVERT
				(
					VARCHAR,
					CONVERT(DECIMAL(15,2), (AUX1.[FATURAMENTO] / AUX2.[TOTAL]) *100, 2)
				), 
			' %'
		) AS PERCENTUAL
FROM
	(SELECT TP.[SABOR], YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
	FROM [ITENS NOTAS FISCAIS] INF
		INNER JOIN [TABELA DE PRODUTOS] TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
		INNER JOIN [NOTAS FISCAIS] NF
			ON INF.[NUMERO] = NF.[NUMERO]
	WHERE YEAR(NF.[DATA]) = 2016
	GROUP BY TP.[SABOR], YEAR(NF.[DATA])) AUX1 -- QUERY AUXILIAR 1
	INNER JOIN
		(SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS TOTAL
		FROM [ITENS NOTAS FISCAIS] INF
			INNER JOIN [TABELA DE PRODUTOS] TP
				ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
			INNER JOIN [NOTAS FISCAIS] NF
				ON INF.[NUMERO] = NF.[NUMERO]
		WHERE YEAR(NF.[DATA]) = 2016
		GROUP BY YEAR(NF.[DATA])) AUX2 -- QUERY AUXILIAR 2
	ON AUX1.[ANO] = AUX2.[ANO]
ORDER BY AUX1.[FATURAMENTO] DESC


-- EXERCICIO PARA VER AS VENDAS POR TAMANHO
-- APENSA SUBSTITUIDO O SABOR POR TAMANHO NA QUERY AUXILIAR 1
SELECT 
	AUX1.[TAMANHO], 
	AUX1.[ANO], 
	CONVERT(DECIMAL(15,2), AUX1.[FATURAMENTO]) AS FATURAMENTO, 
	CONCAT
		(
			CONVERT
				(
					VARCHAR,
					CONVERT(DECIMAL(15,2), (AUX1.[FATURAMENTO] / AUX2.[TOTAL]) *100, 2)
				), 
			' %'
		) AS PERCENTUAL
FROM
	(SELECT TP.[TAMANHO], YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS FATURAMENTO
	FROM [ITENS NOTAS FISCAIS] INF
		INNER JOIN [TABELA DE PRODUTOS] TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
		INNER JOIN [NOTAS FISCAIS] NF
			ON INF.[NUMERO] = NF.[NUMERO]
	WHERE YEAR(NF.[DATA]) = 2016
	GROUP BY TP.[TAMANHO], YEAR(NF.[DATA])) AUX1 -- QUERY AUXILIAR 1
	INNER JOIN
		(SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.[QUANTIDADE] * INF.[PREÇO]) AS TOTAL
		FROM [ITENS NOTAS FISCAIS] INF
			INNER JOIN [TABELA DE PRODUTOS] TP
				ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
			INNER JOIN [NOTAS FISCAIS] NF
				ON INF.[NUMERO] = NF.[NUMERO]
		WHERE YEAR(NF.[DATA]) = 2016
		GROUP BY YEAR(NF.[DATA])) AUX2 -- QUERY AUXILIAR 2
	ON AUX1.[ANO] = AUX2.[ANO]
ORDER BY AUX1.[FATURAMENTO] DESC