SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE 
	WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END AS CLASSIFICAÇÃO
FROM
[TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE 
	WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END AS CLASSIFICAÇÃO,
AVG([PREÇO DE LISTA]) AS MÉDIA
FROM [TABELA DE PRODUTOS]
GROUP BY [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO' 
	END

SELECT YEAR(DATA), COUNT(*) FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)



SELECT [NOME],
CASE
	WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTO'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVEN'
	ELSE 'CRIANÇA'
END AS [FAIXA ETÁRIA]
FROM [TABELA DE CLIENTES]
ORDER BY [DATA DE NASCIMENTO]